//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_LOG_DB
    {
        public int LOG_ID { get; set; }
        public string USER_ACTION { get; set; }
        public string ACTIVITY_USER { get; set; }
        public string BRANCH { get; set; }
        public string SCREEN { get; set; }
        public string LOG_DATE { get; set; }
        public Nullable<System.TimeSpan> LOG_TIME { get; set; }
        public string IP_ADDRESS { get; set; }
        public string ACTION_STATUS { get; set; }
    }
}
