//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public int Id { get; set; }
        public Nullable<int> QuantityRequested { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string RequestedBy { get; set; }
        public string AuthorizedBy { get; set; }
        public Nullable<System.DateTime> DateAuthorized { get; set; }
        public Nullable<int> QuantityIssued { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public string AuthorizationStatus { get; set; }
        public Nullable<System.DateTime> AuthorizationDate { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> CurrentQuantityId { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> RequestStatusId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
    }
}
