//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTable
    {
        public int StockId { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public string StockedBy { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> CurrentQuantityId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public string AuthorizationStatus { get; set; }
        public Nullable<System.DateTime> AuthorizationDate { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
    }
}
