//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDBEntities : DbContext
    {
        public TestDBEntities()
            : base("name=TestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVITY_LOG_DB> ACTIVITY_LOG_DB { get; set; }
        public virtual DbSet<Authorizer> Authorizers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<EmailRequest> EmailRequests { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ReorderLevel> ReorderLevels { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<StockTable> StockTables { get; set; }
        public virtual DbSet<TRANSACTIONS_HISTORY_DB> TRANSACTIONS_HISTORY_DB { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
