//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONS_HISTORY_DB
    {
        public int LOG_ID { get; set; }
        public string RECORD_ID { get; set; }
        public string RECORD_TABLE { get; set; }
        public string OLD_DATA { get; set; }
        public string NEW_DATA { get; set; }
        public string ACTION_MAKER { get; set; }
        public Nullable<System.DateTime> ACTION_DATE { get; set; }
    }
}
